# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['hello']

# %% ../00_core.ipynb 3
def hello(name=None):
    """Say hello, optionally to someone."""
    if name:
        return f"hello {name}"
    else:
        return "hello"
